name: Application bug report
description: Create a bug report to help us fix an issue in Path of Building
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting an issue.
        Please try to fill in as much of the form below as you're able to. Some of the fields marked with an asterisk (*) are required.
  - type: checkboxes
    id: version
    attributes:
      label: Check version
      options:
        - label: I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)
          required: true
  - type: checkboxes
    id: duplicates
    attributes:
      label: Check for duplicates
      options:
        - label: I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)
          required: true
  - type: textarea
    id: expected
    attributes:
      label: How is Path of Building expected to behave?
      description: Please write a clear and concise description of what should happen.
      placeholder: E.g. When I resize PoB all [...] should be accessible.
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: How does Path of Building behave?
      description: Please write a clear and concise description of what actually happens.
      placeholder: E.g. When I resize PoB some [...] become inaccessible. 
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: How to reproduce the issue
      description: Please provide step-by-step instructions.
      placeholder: |
        E.g.
        1. Select [...] as the main skill.
        2. Switch to the items tab.
        3. Remove the main skill group.
        4. [...].
    validations:
      required: false
  - type: textarea
    id: build_code
    attributes:
      label: Character build code
      description: Always provide a build code that exhibits the bug you want to report, even if it is not specific to a particular build. This helps us greatly to reproduce bugs faster.
      placeholder: This can be either a code copied from the "Import/Export Build" tab or a link to a shared build.
      render: shell
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Screenshots
      description: Always provide screenshots of the problem if possible. GIFs or short videos are also okay, if the bug cannot be displayed in a still image.
      placeholder: In this text area, you can attach files/images (copy paste) directly, or link to them if they're hosted elsewhere instead.
    validations:
      required: false
